/* tslint:disable */
/* eslint-disable */
/**
 * ErcWorld Marketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { ErcWorldUserBo } from '../models';
import { UsersBoBody } from '../models';
import { UsersBoBody1 } from '../models';
import { UsersBoBody2 } from '../models';
/**
 * BoUserApi - axios parameter creator
 * @export
 */
export const BoUserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Roles: admin
         * @summary Get User Profile
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersBoMeGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/bo/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Roles: admin
         * @summary Set User Profile
         * @param {UsersBoBody} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersBoPut: async (body?: UsersBoBody, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/bo`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Roles: admin
         * @summary Get User Profile
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersBoUserIdGet: async (userId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            if (userId === null || userId === undefined) {
                throw new RequiredError('userId','Required parameter userId was null or undefined when calling usersBoUserIdGet.');
            }
            const localVarPath = `/users/bo/{userId}`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BoUserApi - functional programming interface
 * @export
 */
export const BoUserApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Roles: admin
         * @summary Get User Profile
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersBoMeGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ErcWorldUserBo>>> {
            const localVarAxiosArgs = await BoUserApiAxiosParamCreator(configuration).usersBoMeGet(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Roles: admin
         * @summary Set User Profile
         * @param {UsersBoBody} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersBoPut(body?: UsersBoBody, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ErcWorldUserBo>>> {
            const localVarAxiosArgs = await BoUserApiAxiosParamCreator(configuration).usersBoPut(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Roles: admin
         * @summary Get User Profile
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersBoUserIdGet(userId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ErcWorldUserBo>>> {
            const localVarAxiosArgs = await BoUserApiAxiosParamCreator(configuration).usersBoUserIdGet(userId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * BoUserApi - factory interface
 * @export
 */
export const BoUserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Roles: admin
         * @summary Get User Profile
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersBoMeGet(options?: AxiosRequestConfig): Promise<AxiosResponse<ErcWorldUserBo>> {
            return BoUserApiFp(configuration).usersBoMeGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Roles: admin
         * @summary Set User Profile
         * @param {UsersBoBody} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersBoPut(body?: UsersBoBody, options?: AxiosRequestConfig): Promise<AxiosResponse<ErcWorldUserBo>> {
            return BoUserApiFp(configuration).usersBoPut(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Roles: admin
         * @summary Get User Profile
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersBoUserIdGet(userId: number, options?: AxiosRequestConfig): Promise<AxiosResponse<ErcWorldUserBo>> {
            return BoUserApiFp(configuration).usersBoUserIdGet(userId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * BoUserApi - object-oriented interface
 * @export
 * @class BoUserApi
 * @extends {BaseAPI}
 */
export class BoUserApi extends BaseAPI {
    /**
     * Roles: admin
     * @summary Get User Profile
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BoUserApi
     */
    public async usersBoMeGet(options?: AxiosRequestConfig) : Promise<AxiosResponse<ErcWorldUserBo>> {
        return BoUserApiFp(this.configuration).usersBoMeGet(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Roles: admin
     * @summary Set User Profile
     * @param {UsersBoBody} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BoUserApi
     */
    public async usersBoPut(body?: UsersBoBody, options?: AxiosRequestConfig) : Promise<AxiosResponse<ErcWorldUserBo>> {
        return BoUserApiFp(this.configuration).usersBoPut(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Roles: admin
     * @summary Get User Profile
     * @param {number} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BoUserApi
     */
    public async usersBoUserIdGet(userId: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<ErcWorldUserBo>> {
        return BoUserApiFp(this.configuration).usersBoUserIdGet(userId, options).then((request) => request(this.axios, this.basePath));
    }
}
