/* tslint:disable */
/* eslint-disable */
/**
 * ErcWorld Marketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AuctionPrice } from './auction-price';
import { TokenUser } from './token-user';
/**
 * 
 * @export
 * @interface Auction
 */
export interface Auction {
    /**
     * 
     * @type {number}
     * @memberof Auction
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof Auction
     */
    startTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Auction
     */
    endTime?: Date;
    /**
     * 
     * @type {TokenUser}
     * @memberof Auction
     */
    seller?: TokenUser | null;
    /**
     * Token Price
     * @type {AuctionPrice}
     * @memberof Auction
     */
    price?: AuctionPrice | null;
}
