/* tslint:disable */
/* eslint-disable */
/**
 * ErcWorld Marketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Currency } from './currency';
/**
 * Price
 * @export
 * @interface CurrencyValue
 */
export interface CurrencyValue {
    /**
     * The message
     * @type {Currency}
     * @memberof CurrencyValue
     */
    currency?: Currency;
    /**
     * Value
     * @type {number}
     * @memberof CurrencyValue
     */
    value?: number;
    /**
     * Value
     * @type {number}
     * @memberof CurrencyValue
     */
    usdValue?: number | null;
}
