/* tslint:disable */
/* eslint-disable */
/**
 * ErcWorld Marketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ErcWorldUser } from './erc-world-user';
/**
 * 
 * @export
 * @interface ErcWorldUserDttResponse
 */
export interface ErcWorldUserDttResponse {
    /**
     * Total
     * @type {number}
     * @memberof ErcWorldUserDttResponse
     */
    recordsTotal?: number;
    /**
     * Filtered
     * @type {number}
     * @memberof ErcWorldUserDttResponse
     */
    recordsFiltered?: number;
    /**
     * Data
     * @type {Array<ErcWorldUser>}
     * @memberof ErcWorldUserDttResponse
     */
    data?: Array<ErcWorldUser> | null;
}
