/* tslint:disable */
/* eslint-disable */
/**
 * ErcWorld Marketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserMessenger } from './user-messenger';
import { UserSetting } from './user-setting';
/**
 * 
 * @export
 * @interface ErcWorldUser
 */
export interface ErcWorldUser {
    /**
     * User Internal ID
     * @type {number}
     * @memberof ErcWorldUser
     */
    id?: number;
    /**
     * User Internal Name
     * @type {string}
     * @memberof ErcWorldUser
     */
    username?: string | null;
    /**
     * User Wallet
     * @type {string}
     * @memberof ErcWorldUser
     */
    wallet?: string;
    /**
     * User Bio under the avatarImg in User profile page
     * @type {string}
     * @memberof ErcWorldUser
     */
    userbio?: string | null;
    /**
     * Background image of the user profile
     * @type {string}
     * @memberof ErcWorldUser
     */
    coverImg?: string | null;
    /**
     * Avatar image of the user profile
     * @type {string}
     * @memberof ErcWorldUser
     */
    avatarImg?: string | null;
    /**
     * User followers
     * @type {number}
     * @memberof ErcWorldUser
     */
    followers?: number;
    /**
     * User following
     * @type {number}
     * @memberof ErcWorldUser
     */
    following?: number;
    /**
     * 
     * @type {Date}
     * @memberof ErcWorldUser
     */
    createdate?: Date;
    /**
     * User followers
     * @type {number}
     * @memberof ErcWorldUser
     */
    likes?: number;
    /**
     * User following
     * @type {number}
     * @memberof ErcWorldUser
     */
    liked?: number;
    /**
     * User Email
     * @type {string}
     * @memberof ErcWorldUser
     */
    email?: string | null;
    /**
     * Messengers settings
     * @type {Array<UserMessenger>}
     * @memberof ErcWorldUser
     */
    messengers?: Array<UserMessenger> | null;
    /**
     * Notification and authentication settings
     * @type {UserSetting}
     * @memberof ErcWorldUser
     */
    settings?: UserSetting | null;
}
