/* tslint:disable */
/* eslint-disable */
/**
 * ErcWorld Marketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ErcWorldUserBo
 */
export interface ErcWorldUserBo {
    /**
     * User Internal ID
     * @type {number}
     * @memberof ErcWorldUserBo
     */
    id?: number;
    /**
     * User Internal Name
     * @type {string}
     * @memberof ErcWorldUserBo
     */
    username?: string | null;
    /**
     * User Pass
     * @type {string}
     * @memberof ErcWorldUserBo
     */
    password?: string | null;
    /**
     * User Wallet
     * @type {string}
     * @memberof ErcWorldUserBo
     */
    wallet?: string;
    /**
     * User Bio under the avatarImg in User profile page
     * @type {string}
     * @memberof ErcWorldUserBo
     */
    fullname?: string | null;
    /**
     * Background image of the user profile
     * @type {string}
     * @memberof ErcWorldUserBo
     */
    email?: string | null;
    /**
     * Avatar image of the user profile
     * @type {string}
     * @memberof ErcWorldUserBo
     */
    pic?: string | null;
    /**
     * Avatar image of the user profile
     * @type {Array<string>}
     * @memberof ErcWorldUserBo
     */
    roles?: Array<string> | null;
    /**
     * Avatar image of the user profile
     * @type {Array<string>}
     * @memberof ErcWorldUserBo
     */
    permissions?: Array<string> | null;
    /**
     * Avatar image of the user profile
     * @type {number}
     * @memberof ErcWorldUserBo
     */
    status?: number | null;
    /**
     * User Wallet
     * @type {string}
     * @memberof ErcWorldUserBo
     */
    occupation?: string | null;
}
