/* tslint:disable */
/* eslint-disable */
/**
 * ErcWorld Marketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * System Error
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * The message
     * @type {string}
     * @memberof ModelError
     */
    message?: string;
    /**
     * Validation Errors
     * @type {Array<string>}
     * @memberof ModelError
     */
    errors?: Array<string> | null;
}
