/* tslint:disable */
/* eslint-disable */
/**
 * ErcWorld Marketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Nft } from './nft';
/**
 * 
 * @export
 * @interface NftDttResponse
 */
export interface NftDttResponse {
    /**
     * Total
     * @type {number}
     * @memberof NftDttResponse
     */
    recordsTotal?: number;
    /**
     * Filtered
     * @type {number}
     * @memberof NftDttResponse
     */
    recordsFiltered?: number;
    /**
     * Data
     * @type {Array<Nft>}
     * @memberof NftDttResponse
     */
    data?: Array<Nft> | null;
}
