/* tslint:disable */
/* eslint-disable */
/**
 * ErcWorld Marketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * '721' as \"type\", eventid, parentcontractaddress, calleraddress, creatoraddress, tokenid, royaltyfee, 0 supply, uri, createdate, eventtimestamp_unix, eventtimestamp
 * @export
 * @interface Nft
 */
export interface Nft {
    /**
     * 
     * @type {string}
     * @memberof Nft
     */
    type?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Nft
     */
    eventid?: number;
    /**
     * 
     * @type {string}
     * @memberof Nft
     */
    parentcontractaddress?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Nft
     */
    calleraddress?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Nft
     */
    creatoraddress?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Nft
     */
    tokenid?: number;
    /**
     * 
     * @type {number}
     * @memberof Nft
     */
    royaltyfee?: number;
    /**
     * 
     * @type {number}
     * @memberof Nft
     */
    supply?: number;
    /**
     * 
     * @type {string}
     * @memberof Nft
     */
    uri?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Nft
     */
    createdate?: Date;
    /**
     * 
     * @type {number}
     * @memberof Nft
     */
    eventtimestampUnix?: number;
    /**
     * 
     * @type {Date}
     * @memberof Nft
     */
    eventtimestamp?: Date;
}
