/* tslint:disable */
/* eslint-disable */
/**
 * ErcWorld Marketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Auction } from './auction';
import { Collection } from './collection';
import { CurrencyValue } from './currency-value';
import { NftStandard } from './nft-standard';
import { TokenAvailability } from './token-availability';
import { TokenSale } from './token-sale';
import { TokenUser } from './token-user';
/**
 * 
 * @export
 * @interface Token
 */
export interface Token {
    /**
     * Token Name
     * @type {string}
     * @memberof Token
     */
    id?: string;
    /**
     * Token Name
     * @type {string}
     * @memberof Token
     */
    name?: string;
    /**
     * NFT Standard
     * @type {NftStandard}
     * @memberof Token
     */
    standard?: NftStandard | null;
    /**
     * Token Description
     * @type {string}
     * @memberof Token
     */
    description?: string | null;
    /**
     * Favorite Count
     * @type {number}
     * @memberof Token
     */
    favoriteCount?: number;
    /**
     * 
     * @type {TokenUser}
     * @memberof Token
     */
    creator?: TokenUser | null;
    /**
     * 
     * @type {Collection}
     * @memberof Token
     */
    collection?: Collection | null;
    /**
     * 
     * @type {number}
     * @memberof Token
     */
    royalty?: number;
    /**
     * 
     * @type {TokenAvailability}
     * @memberof Token
     */
    availability?: TokenAvailability | null;
    /**
     * 
     * @type {Auction}
     * @memberof Token
     */
    auction?: Auction | null;
    /**
     * Token Price
     * @type {CurrencyValue}
     * @memberof Token
     */
    price?: CurrencyValue | null;
    /**
     * Token Sell Methods
     * @type {TokenSale}
     * @memberof Token
     */
    sale?: TokenSale | null;
}
