/* tslint:disable */
/* eslint-disable */
/**
 * ErcWorld Marketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TokenAvailability
 */
export interface TokenAvailability {
    /**
     * Total
     * @type {number}
     * @memberof TokenAvailability
     */
    total?: number;
    /**
     * Current
     * @type {number}
     * @memberof TokenAvailability
     */
    current?: number;
}
