/* tslint:disable */
/* eslint-disable */
/**
 * ErcWorld Marketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TokenUser
 */
export interface TokenUser {
    /**
     * Creator Name
     * @type {string}
     * @memberof TokenUser
     */
    name?: string;
    /**
     * Wallet
     * @type {string}
     * @memberof TokenUser
     */
    wallet?: string | null;
    /**
     * Avatar Url
     * @type {string}
     * @memberof TokenUser
     */
    avatar?: string | null;
}
