/* tslint:disable */
/* eslint-disable */
/**
 * ErcWorld Marketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Token Group
 * @export
 * @enum {string}
 */
export enum TokenGroup {
    Auction = 'auction',
    Transferred = 'transferred',
    Purchases = 'purchases',
    Favorites = 'favorites',
    Created = 'created'
}

