/* tslint:disable */
/* eslint-disable */
/**
 * ErcWorld Marketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CurrencyValue } from './currency-value';
import { TokenUser } from './token-user';
/**
 * 
 * @export
 * @interface TokenBid
 */
export interface TokenBid {
    /**
     * Token Seller
     * @type {TokenUser}
     * @memberof TokenBid
     */
    from?: TokenUser;
    /**
     * Token Seller
     * @type {number}
     * @memberof TokenBid
     */
    timestamp?: number;
    /**
     * Token Seller
     * @type {CurrencyValue}
     * @memberof TokenBid
     */
    price?: CurrencyValue | null;
}
