/* tslint:disable */
/* eslint-disable */
/**
 * ErcWorld Marketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UploaduserimagesWalletAddressBody
 */
export interface UploaduserimagesWalletAddressBody {
    /**
     * User Wallet
     * @type {string}
     * @memberof UploaduserimagesWalletAddressBody
     */
    wallet?: string;
    /**
     * 
     * @type {Blob}
     * @memberof UploaduserimagesWalletAddressBody
     */
    avatarImgFile?: Blob;
    /**
     * 
     * @type {Blob}
     * @memberof UploaduserimagesWalletAddressBody
     */
    coverImgFile?: Blob;
}
