/* tslint:disable */
/* eslint-disable */
/**
 * ErcWorld Marketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UserRole
 */
export interface UserRole {
    /**
     * User Wallet
     * @type {number}
     * @memberof UserRole
     */
    id?: number;
    /**
     * User Wallet
     * @type {string}
     * @memberof UserRole
     */
    title?: string | null;
    /**
     * User Wallet
     * @type {string}
     * @memberof UserRole
     */
    description?: string | null;
}
