/* tslint:disable */
/* eslint-disable */
/**
 * ErcWorld Marketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UserNotification
 */
export interface UserNotification {
    /**
     * Notification Name
     * @type {string}
     * @memberof UserNotification
     */
    notificationName?: string;
    /**
     * Email notification enabled
     * @type {boolean}
     * @memberof UserNotification
     */
    emailNotification?: boolean;
    /**
     * Push notification enabled
     * @type {boolean}
     * @memberof UserNotification
     */
    pushNotification?: boolean;
}
