/* tslint:disable */
/* eslint-disable */
/**
 * ErcWorld Marketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UserNote
 */
export interface UserNote {
    /**
     * User Internal ID
     * @type {number}
     * @memberof UserNote
     */
    id?: number;
    /**
     * User Internal Name
     * @type {string}
     * @memberof UserNote
     */
    note?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof UserNote
     */
    createdate?: Date;
    /**
     * 
     * @type {string}
     * @memberof UserNote
     */
    createuser?: string;
}
