/* tslint:disable */
/* eslint-disable */
/**
 * ErcWorld Marketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserMessenger } from './user-messenger';
import { UserSetting } from './user-setting';
/**
 * 
 * @export
 * @interface UserRequest
 */
export interface UserRequest {
    /**
     * User Internal Name
     * @type {string}
     * @memberof UserRequest
     */
    username?: string | null;
    /**
     * User Wallet
     * @type {string}
     * @memberof UserRequest
     */
    wallet?: string | null;
    /**
     * User Bio under the avatarImg in User profile page
     * @type {string}
     * @memberof UserRequest
     */
    userbio?: string | null;
    /**
     * User Email
     * @type {string}
     * @memberof UserRequest
     */
    email?: string | null;
    /**
     * Messengers settings
     * @type {Array<UserMessenger>}
     * @memberof UserRequest
     */
    messengers?: Array<UserMessenger> | null;
    /**
     * Notification and authentication settings
     * @type {UserSetting}
     * @memberof UserRequest
     */
    settings?: UserSetting | null;
}
