/* tslint:disable */
/* eslint-disable */
/**
 * ErcWorld Marketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserNotification } from './user-notification';
/**
 * 
 * @export
 * @interface UserSetting
 */
export interface UserSetting {
    /**
     * Two factor authentication enabled
     * @type {boolean}
     * @memberof UserSetting
     */
    twoFactorEnabled?: boolean | null;
    /**
     * Two factor authentication enabled
     * @type {boolean}
     * @memberof UserSetting
     */
    antiPhishingEnabled?: boolean | null;
    /**
     * Notifications settings
     * @type {Array<UserNotification>}
     * @memberof UserSetting
     */
    notifications?: Array<UserNotification> | null;
}
