/* tslint:disable */
/* eslint-disable */
/**
 * ErcWorld Marketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserMessenger } from './user-messenger';
import { UserRequest } from './user-request';
import { UserSetting } from './user-setting';
/**
 * 
 * @export
 * @interface UsersMeBody1
 */
export interface UsersMeBody1 extends UserRequest {
}
