/* tslint:disable */
/* eslint-disable */
/**
 * ErcWorld Marketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UserHistory
 */
export interface UserHistory {
    /**
     * 
     * @type {number}
     * @memberof UserHistory
     */
    usersId?: number;
    /**
     * 
     * @type {string}
     * @memberof UserHistory
     */
    useragent?: string;
    /**
     * 
     * @type {string}
     * @memberof UserHistory
     */
    ip?: string;
    /**
     * 
     * @type {Date}
     * @memberof UserHistory
     */
    createdate?: Date;
    /**
     * 
     * @type {string}
     * @memberof UserHistory
     */
    os?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserHistory
     */
    client?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserHistory
     */
    device?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserHistory
     */
    brand?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserHistory
     */
    model?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserHistory
     */
    bot?: string | null;
}
