/* tslint:disable */
/* eslint-disable */
/**
 * ErcWorld Marketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserHistory } from './user-history';
/**
 * 
 * @export
 * @interface UserHistoryDttResponse
 */
export interface UserHistoryDttResponse {
    /**
     * Total
     * @type {number}
     * @memberof UserHistoryDttResponse
     */
    recordsTotal?: number;
    /**
     * Filtered
     * @type {number}
     * @memberof UserHistoryDttResponse
     */
    recordsFiltered?: number;
    /**
     * Data
     * @type {Array<UserHistory>}
     * @memberof UserHistoryDttResponse
     */
    data?: Array<UserHistory> | null;
}
