/* tslint:disable */
/* eslint-disable */
/**
 * ErcWorld Marketplace
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UsersHistoryRequest
 */
export interface UsersHistoryRequest {
    /**
     * User Id
     * @type {number}
     * @memberof UsersHistoryRequest
     */
    id?: number;
    /**
     * Number of rows
     * @type {number}
     * @memberof UsersHistoryRequest
     */
    count?: number;
}
